[package]
name = "btcmap-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Compiler settings and optimizations
[profile.release]
opt-level = "s"
strip = "symbols"

[dependencies]

# https://github.com/actix/actix-web/releases
actix-web = { version = "4.4.1", default-features = false, features = ["macros", "compress-brotli"] }

# https://github.com/rusqlite/rusqlite/releases
rusqlite = { version = "0.30.0", default-features = false, features = ["bundled", "time"] }

# https://github.com/seanmonstar/reqwest/releases
reqwest = { version = "0.11.23", default-features = false, features = ["rustls-tls", "json"] }

# https://github.com/serde-rs/serde/releases
serde = { version = "1.0.195", default-features = false, features = ["derive"] }

# https://github.com/serde-rs/json/releases
serde_json = { version = "1.0.111", default-features = false }

# https://github.com/time-rs/time/releases
time = { version = "0.3.31", default-features = false, features = ["macros", "serde-well-known"] }

# https://crates.io/crates/directories
directories = { version = "5.0.1", default-features = false }

# https://github.com/tokio-rs/tracing/releases
tracing = { version = "0.1.40", default-features = false }

# https://github.com/tokio-rs/tracing/releases
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["json", "env-filter", "fmt"] }

# https://github.com/Michael-F-Bryan/include_dir/tags
include_dir = { version = "0.7.3", default-features = false }

# https://github.com/tokio-rs/tokio/releases
tokio = { version = "1.35.1", default-features = false, features = ["macros"] }

# https://github.com/georust/geojson/tags
geojson = { version = "0.24.1", default-features = false, features = ["geo-types"] }

# https://github.com/georust/geo/blob/main/geo/CHANGES.md
geo = { version = "0.27.0", default-features = false }

# https://github.com/rust-lang/futures-rs/releases
futures-util = { version = "0.3.30", default-features = false }

# https://github.com/hyperium/http/releases
http = { version = "0.2.9", default-features = false }

# https://github.com/bikeshedder/deadpool/tags
deadpool-sqlite = { version = "0.7.0", default-features = false, features = ["rt_tokio_1"] }

# https://github.com/AaronErhardt/actix-governor/releases
actix-governor = { version = "0.5.0", default-features = false }