[package]
name = "btcmap-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = "symbols"

[dependencies]

# https://github.com/actix/actix-web/releases
actix-web = { version = "4.3.0", default-features = false, features = ["macros", "compress-brotli"] }

# https://github.com/rusqlite/rusqlite/releases
rusqlite = { version = "0.28.0", features = ["bundled"] }

# https://github.com/seanmonstar/reqwest/releases
reqwest = { version = "0.11.14", default-features = false, features = ["rustls-tls", "json", "blocking"] }

# https://github.com/serde-rs/serde/releases
serde = { version = "1.0.152", features = ["derive"] }

# https://github.com/serde-rs/json/releases
serde_json = { version = "1.0.91", features = ["preserve_order"] }

# https://github.com/time-rs/time/releases
time = { version = "0.3.17", features = ["formatting", "parsing", "macros", "serde-well-known"] }

# https://crates.io/crates/directories
directories = "4.0.1"

# https://github.com/tokio-rs/tracing/releases
tracing = "0.1.37"

# https://github.com/tokio-rs/tracing/releases
tracing-subscriber = { version = "0.3.16", features = ["json", "env-filter"] }

# https://github.com/Michael-F-Bryan/include_dir/tags
include_dir = "0.7.3"

# https://github.com/tokio-rs/tokio/releases
tokio = { version = "1.24.1", features = ["time", "macros", "rt-multi-thread"] }

# https://github.com/georust/geojson/tags
geojson = "0.24.0"

# https://github.com/georust/geo/tags
geo = "0.24.1"

# https://github.com/utkarshkukreti/diff.rs/tags
diff = "0.1.13"

# https://github.com/rust-lang/futures-rs/releases
futures-util = "0.3.28"