[package]
name = "btcmap-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = "symbols"

[dependencies]
actix-web = { version = "4.2.1", default-features = false, features = ["macros", "compress-brotli"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3.9", features = ["formatting", "parsing", "macros"] }
directories = "4.0.1"
log = "0.4.0"
env_logger = "0.8.4"
include_dir = "0.7.2"
tokio = { version = "1.21.2", features = ["time", "macros", "rt-multi-thread"] }
derive_more = "0.99.17"
geojson = "0.24.0"
geo = "0.23.1"