name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-linux-musl
        default: true
        override: true
        
    - name: Run tests
      run: cargo test --release --verbose
      
    - name: Build
      run: cargo build --release --verbose
      
    - name: Create preview release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: 'preview'
        prerelease: true
        title: 'preview'
        files: 'target/release/btcmap-api'
